name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn
      - name: Install dependencies
        run: |
          n=0
          until [ $n -ge 3 ]
          do
            yarn install && echo "done" && break
            n=$((n+1))
            echo "Retry $n/3..."
            sleep 15
          done
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Docs
        run: yarn gh-pages
      - name: Test
        run: node_modules/.bin/serve --listen 3000 gh-pages/ & yarn test
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        if: github.event_name == 'push'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
      - name: Publish npm
        if: github.event_name == 'push'
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
